### ISSUE TITLE
twrp recovery too large

### ISSUE THREAD

**Issue by zqm64** [exynos5410/android_device_samsung_exynos5410-common#1]
error: +/mnt/disk-1/jenkins/workspace/LineageOS-Builds/14.1/Samsung/GT-I9500/target/product/ja3gxx/recovery.img too large (9121792 > [8650752 - 88704])

**Comment by Alberto96** [comment]
You can't build the ROM without "WITH_TWRP" if you don't "hack" the recovery size.
